### ISSUE TITLE
single node example

### ISSUE THREAD

**Issue by drewdeally** [cockroachlabs-field/docker-examples#7]
version: "3.5"
services:
   
    node_1:
        container_name: node_1
        image: cockroachdb/cockroach:v19.2.4
        volumes:
           - ./data/node_1:/cockroach/cockroach-data
        command: start-single-node --insecure
        ports:
         - "26257:26257"
         - "8080:8080"
        networks:
            cockroachdb_net:
                aliases:
                   - node_1

networks:
    cockroachdb_net:
        driver: bridge

**Comment by timveil** [comment]
added an example @drewdeally ...  https://github.com/timveil-cockroach/docker-examples/tree/master/example-single-node

**Comment by drewdeally** [comment]
Thank You
